import "./globals.css";

export const metadata = {
  title: "Food Health",
  description: "Generated by Philemon Tebo and Zenith Bossadi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
